version: "2.4"
services:
  web:
    container_name: "pair_trader_webapp"
    mem_limit: 6G
    restart: unless-stopped
    command:
      - default
    build: .
    # Mapping of container port to host
    ports:
      - "8091:5000"
    environment:
      TZ: "Europe/London"
